version: '3'
services:
  app:
    build: .
    ports:
      - "8181:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: bash -c 'php artisan migrate && php artisan serve --host 0.0.0.0'
    depends_on:
      - db
    links:
      - db
  db:
    image: "mysql:8.0.21"
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=task-manager
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      EXTERNAL_IP: 172.26.0.3
      MYSQL_ROOT_PASSWORD: pass